### ISSUE TITLE
Example q-script

### ISSUE THREAD

**Issue by nick-mospan** [mortensorensen/QInteractiveBrokers#1]
Thanks for putting this up on git hub, I'm impressed! Could you add a q-script with bindings that you use and examples of q-scripts with queries / place order to get me started?

**Comment by mortensorensen** [comment]
Hi Nick. I have added an example q script that connects to IB and subscribes to ticks. The C++ files are basically just a wrapper around the IB API. Should be straightforward to implement other functions. Let me know if you have any issues. Thanks
