### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bluethoughts** [mortensorensen/QInteractiveBrokers#3]
Hi,

Thanks for the great work.
I am getting the below error when installing in my Centos7 64 bit. Googled for a while but no sound solution. Would you have any idea? Thanks!

> [build]$ make
Scanning dependencies of target qib.0.0.1
[ 33%] Building CXX object CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o
c++: error: i386: No such file or directory
c++: error: unrecognized command line option ‘-arch’
make[2]: *** [CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/qib.0.0.1.dir/all] Error 2
make: *** [all] Error 2

**Comment by mortensorensen** [comment]
Hi,

Looks like the arch flags are being set to i386 even though you're on 64 bit. Can go try to comment out some of the lines that set archs in CMakeList.txt? Will be back from holiday next week and will have a look too.

Thanks

**Comment by bluethoughts** [comment]
Thanks mortensorensen! It seems working after commenting out 
`set` (ARCHFLAGS "-arch i386")
