### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by bluethoughts** [mortensorensen/QInteractiveBrokers#4]
Hi mortensorensen,

May I know what compilers and their versions you using?
I have tried GCC and Clang but both failed. It seems the codes are correct but just not compatible with the compilers I am using.

Logs attached below.

Thanks and Happy New Year!

> -- The CXX compiler identification is Clang 3.5.0
> -- The C compiler identification is Clang 3.5.0

> [bluethoughts@vm build]$ make
> [ 33%] Building CXX object CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/src/IBClient.cpp:1:
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/src/IBClient.h:4:
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/third_party/ib/IBJts/source/PosixClient/Shared/EWrapper.h:8:
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/third_party/ib/IBJts/source/PosixClient/Shared/IBString.h:8:
> In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/string:52:
> In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/basic_string.h:2815:
> In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ext/string_conversions.h:43:
> /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cstdio:120:11: error: no member named 'gets' in the global namespace
>   using ::gets;
>         ~~^
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/src/IBClient.cpp:5:
> /home/bluethoughts/projects/QInteractiveBrokers-master/third_party/ib/IBJts/source/PosixClient/Shared/EClientSocketBaseImpl.h:2807:14: warning: 56
>       enumeration values not handled in switch: 'BID_SIZE', 'ASK_SIZE', 'LAST_SIZE'... [-Wswitch]
>                                         switch( (TickType)tickTypeInt) {
>                                                 ^
> 1 warning and 1 error generated.
> make[2]: *** [CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o] Error 1
> make[1]: *** [CMakeFiles/qib.0.0.1.dir/all] Error 2
> make: *** [all] Error 2
> 
> 
> -- The CXX compiler identification is GNU 4.8.5
> -- The C compiler identification is GNU 4.8.5
> 
> [bluethoughts@vm build]$ make
> Scanning dependencies of target qib.0.0.1
> [ 33%] Building CXX object CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o
> In file included from /home/bluethoughts/projects/QInteractiveBrokers-master/src/IBClient.h:5:0,
>                  from /home/bluethoughts/projects/QInteractiveBrokers-master/src/IBClient.cpp:1:
> /home/bluethoughts/projects/QInteractiveBrokers-master/src/helpers.h: In function ‘auto partial(F&&, V&&)’:
> /home/bluethoughts/projects/QInteractiveBrokers-master/src/helpers.h:40:60: error: expansion pattern ‘auto&&’ contains no argument packs
>      [f=std::forward<F>(f), v=std::forward<V>(v)](auto&&... args)
>                                                             ^
> /home/bluethoughts/projects/QInteractiveBrokers-master/src/helpers.h: In lambda function:
> /home/bluethoughts/projects/QInteractiveBrokers-master/src/helpers.h:42:30: error: ‘args’ was not declared in this scope
>          return f(v, decltype(args)(args)...);
>                               ^
> make[2]: *** [CMakeFiles/qib.0.0.1.dir/src/IBClient.cpp.o] Error 1
> make[1]: *** [CMakeFiles/qib.0.0.1.dir/all] Error 2
> make: *** [all] Error 2

**Comment by mortensorensen** [comment]
Thanks for reporting the issue. I am using Clang on MacOS. I have only tested the code on MacOS so far, but will try to compile it on Linux tomorrow.

```
$ c++ -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mortensorensen** [comment]
Hi, you should be able to compile it on Linux with the latest commit. I have added an example `Dockerfile` which has the necessary packages in order to compile a 32-bit binary on a 64-bit system. Let me know if this fixes the issue. Thanks
